version: "3"

services:
  webserver:
    build:
      context: ./airflow_docker
      dockerfile: DockerFile
    image: puckel/docker-airflow:latest
    container_name: az_airflow_container
    volumes:
        - ./dags:/usr/local/airflow/dags
        - ./include:/usr/local/airflow/include
        - ./redash:/usr/local/airflow/redash
    ports:
      - 9003:8080
    networks:
      - backend
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: newdb
    container_name: az_mysql_container
    ports:
      - 9004:3306
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: helloworld
      UPLOAD_LIMIT: 300M
    ports:
      - "9002:80"
    networks:
      - backend
    volumes:
      - ./php-make/upload.ini:/usr/local/etc/php/php.ini

  warehouse:
    image: postgres:12.2
    container_name: az_warehouse
    restart: always
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_PASSWORD: password
      POSTGRES_USER: sde
    volumes:
      # - ./data:/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  
  superset:
    image: tylerfowler/superset
    container_name: az_superset
    restart: always
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "9001:8088"

  postgres-airflow:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER : airflowuser
      POSTGRES_DB : airflowdb
      
      AIRFLOW_SCHEMA: airflow
    expose:
      - 5432
    restart: always
    volumes:
      - ./scripts_postgres:/docker-entrypoint-initdb.d
      # - ./sample_data:/sample_data

  postgres-dbt:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER : dbtuser
      POSTGRES_DB : dbtdb
      DBT_SCHEMA: dbt
      DBT_RAW_DATA_SCHEMA: dbt_raw_data
    expose:
      - 5432
    restart: always
    volumes:
      - ./sample_data:/sample_data

  airflow:
    build: .
    restart: always
    environment: 
      DBT_PROFILES_DIR: /dbt
      AIRFLOW_HOME: /airflow
      AIRFLOW__CORE__DAGS_FOLDER: /airflow/dags
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__DAG_CONCURRENCY: 4
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4
      # AIRFLOW__ADMIN__HIDE_SENSITIVE_VARIABLE_FIELDS: False
      # Postgres details need to match with the values defined in the postgres-airflow service
      POSTGRES_USER: airflowuser
      POSTGRES_PASSWORD: pssd
      POSTGRES_HOST: postgres-airflow
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflowdb
      # postgres-dbt connection details. Required for the inital loading of seed data
      # Credentials need to match with service postgres-dbt
      DBT_POSTGRES_PASSWORD: pssd
      DBT_POSTGRES_USER : dbtuser
      DBT_POSTGRES_DB : dbtdb
      DBT_DBT_SCHEMA: dbt
      DBT_DBT_RAW_DATA_SCHEMA: dbt_raw_data
      DBT_POSTGRES_HOST: postgres-dbt
    depends_on:
      - postgres-airflow
      - postgres-dbt
    ports:
      - 8000:8080
    volumes:
      - ./dbt:/dbt
      - ./airflow:/airflow

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres-airflow
      - postgres-dbt

# dbt container
networks:
  backend:
    driver: "bridge"

    