version: "3"

services:
  webserver:
    build:
      context: ./airflow_docker
      dockerfile: DockerFile
    image: puckel/docker-airflow:latest
    container_name: az_airflow_container
    volumes:
        - ./dags:/usr/local/airflow/dags
        - ./include:/usr/local/airflow/include
        - ./redash:/usr/local/airflow/redash
    ports:
      - 9003:8080
    networks:
      - backend
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: newdb
    container_name: az_mysql_container
    ports:
      - 9004:3306
    networks:
      - backend


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: helloworld
      UPLOAD_LIMIT: 300M
    ports:
      - "9002:80"
    networks:
      - backend
    volumes:
      - ./php-make/upload.ini:/usr/local/etc/php/php.ini

networks:
  backend:
    driver: "bridge"

    